services:
  - type: web
    name: api-gb
    env: node
    plan: free
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ALLOWED_ORIGINS
        sync: false
