name: Database Configuration Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-database-config:
    name: Validate Database Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate .env.example
      run: |
        echo "🔍 Validating .env.example file..."
        if [ ! -f .env.example ]; then
          echo "❌ .env.example file not found"
          exit 1
        fi
        
        # Check if required variables are present
        required_vars=("POSTGRES_USER" "POSTGRES_PASSWORD" "POSTGRES_DB" "DATABASE_URL" "JWT_SECRET" "JWT_EXPIRES_IN")
        for var in "${required_vars[@]}"; do
          if ! grep -q "^${var}=" .env.example; then
            echo "❌ Missing required variable: ${var}"
            exit 1
          else
            echo "✅ Found: ${var}"
          fi
        done

    - name: Validate Docker Compose configuration
      run: |
        echo "🔍 Validating docker-compose.yml..."
        if ! grep -q "POSTGRES_USER.*admin" docker-compose.yml; then
          echo "❌ POSTGRES_USER not set to 'admin' in docker-compose.yml"
          exit 1
        fi
        
        if ! grep -q "POSTGRES_PASSWORD.*GoBarber123" docker-compose.yml; then
          echo "❌ POSTGRES_PASSWORD not set to 'GoBarber123' in docker-compose.yml"
          exit 1
        fi
        
        if ! grep -q "POSTGRES_DB.*nest_db" docker-compose.yml; then
          echo "❌ POSTGRES_DB not set to 'nest_db' in docker-compose.yml"
          exit 1
        fi
        
        echo "✅ Docker Compose configuration is valid"

    - name: Validate CI/CD workflows
      run: |
        echo "🔍 Validating CI/CD workflows..."
        
        # Check ci-cd.yml
        if ! grep -q "POSTGRES_USER: admin" .github/workflows/ci-cd.yml; then
          echo "❌ POSTGRES_USER not set to 'admin' in ci-cd.yml"
          exit 1
        fi
        
        if ! grep -q "POSTGRES_PASSWORD: GoBarber123" .github/workflows/ci-cd.yml; then
          echo "❌ POSTGRES_PASSWORD not set to 'GoBarber123' in ci-cd.yml"
          exit 1
        fi
        
        if ! grep -q "POSTGRES_DB: nest_db" .github/workflows/ci-cd.yml; then
          echo "❌ POSTGRES_DB not set to 'nest_db' in ci-cd.yml"
          exit 1
        fi
        
        echo "✅ CI/CD workflows configuration is valid"

    - name: Test database connection consistency
      run: |
        echo "🔍 Testing database connection consistency..."
        
        # Test localhost connection (for development)
        localhost_url="postgresql://admin:GoBarber123@localhost:5432/nest_db?schema=public"
        echo "✅ Localhost URL format: ${localhost_url}"
        
        # Test Docker internal connection (for containers)
        docker_url="postgresql://admin:GoBarber123@postgres:5432/nest_db?schema=public"
        echo "✅ Docker internal URL format: ${docker_url}"
        
        echo "✅ All database configurations are consistent"

    - name: Summary
      run: |
        echo "🎉 Database configuration validation completed successfully!"
        echo "✅ .env.example is properly configured"
        echo "✅ docker-compose.yml uses consistent credentials"
        echo "✅ CI/CD workflows use consistent credentials"
        echo "✅ All database URLs are properly formatted"
